name: KitMaster
version: '${project.version}'
main: blokplugins.kitroom.Kitroom
api-version: '1.20'
author: blokongithub
website: www.github.com/blokongithub/kitroom
commands:
  kit:
    description: "opens kit menu"
    aliases:
      - kits
      - k
  kitroom:
    description: "opens up the kitroom"
  k1:
    description: "Loads kit 1"
  k2:
    description: "Loads kit 2"
  k3:
    description: "Loads kit 3"
  k4:
    description: "Loads kit 4"
  k5:
    description: "Loads kit 5"
  k6:
    description: "Loads kit 6"
  k7:
    description: "Loads kit 7"
  k8:
    description: "Loads kit 8"
  k9:
    description: "Loads kit 9"
  ec1:
    description: "Loads Ender Chest 1"
  ec2:
    description: "Loads Ender Chest 2"
  ec3:
    description: "Loads Ender Chest 3"
  ec4:
    description: "Loads Ender Chest 4"
  ec5:
    description: "Loads Ender Chest 5"
  ec6:
    description: "Loads Ender Chest 6"
  ec7:
    description: "Loads Ender Chest 7"
  ec8:
    description: "Loads Ender Chest 8"
  ec9:
    description: "Loads Ender Chest 9"
  kitadmin:
    description: "kitroom admin options"
    permission: kitroom.admin
permissions:
  kitroom.admin:
    description: allows /kitadmin
    default: op
  kitroom.viewothers:
    description: allows
    default: op